### ISSUE TITLE
Fix Bodin splash screen

### ISSUE THREAD

**Issue by gmbr3** [gmbr3/ginwet#6]
Bodin splash screen currently shows Tv crackle.

**Comment by korben546** [comment]
I have not experienced this bug yet so it might just be test drive as test drive does glith up the screen on a lot of things

**Comment by korben546** [comment]
has the issue been fixed or is it still unknown why its happening?

**Comment by korben546** [comment]
tested and bug only appears in test drive

**Comment by gmbr3** [comment]
Ok
